super
btw
chrisrust@tes15:~/rustdevelopment$ RUST_BACKTRACE=1 ./hello
thread '<main>' panicked at 'no arg 1', src/libcore/option.rs:298
stack backtrace:
   1:     0x55f658ebf8d0 - sys::backtrace::tracing::imp::write::h19a75f57079ca7d6Eju
   2:     0x55f658ec1ab5 - panicking::default_handler::_<closure>::closure.42502
   3:     0x55f658ec155f - panicking::default_handler::heecbc8b8a021fa9bGwy
   4:     0x55f658eb9316 - sys_common::unwind::begin_unwind_inner::hd4253a1812044857bct
   5:     0x55f658eb94d8 - sys_common::unwind::begin_unwind_fmt::h281339998baa4cbdhbt
   6:     0x55f658ebef01 - rust_begin_unwind
   7:     0x55f658eedbbf - panicking::panic_fmt::h0d7335d3d6686f32zYL
   8:     0x55f658eb76c5 - option::Option<T>::expect::h2201566812756691952
   9:     0x55f658eb70d9 - main::h251d722ddad6812cfaa
  10:     0x55f658ec11e4 - sys_common::unwind::try::try_fn::h16812149991338687188
  11:     0x55f658ebee98 - __rust_try
  12:     0x55f658ec0e70 - rt::lang_start::hc0b5a65f976d4337Uoy
  13:     0x55f658eb88a9 - main
  14:     0x7f9a8363b60f - __libc_start_main
  15:     0x55f658eb6f18 - _start
  16:                0x0 - <unknown>